### ISSUE TITLE
[Core feature request] `fail-fast` and `max-parallel` for matrix strategy

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-workflows-kt#287]
**What feature do you need?**
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel

**Do you have an example usage?**
```yml
strategy:
    fail-fast: false
    max-parallel: 2
    matrix:
        environment:
            - windows-2019
            - windows-2022
            - windows-latest
```
