### ISSUE TITLE
[Core feature request] More sophisticated matrices

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-workflows-kt#297]
**What feature do you need?**
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts-to-create-matrices
Currently only the most simple and flat matrices are supported with the datatype `Map<String, List<String>>`.
But besides that you can take a matrix dimension value from a context variable,
there are also much more advanced matrix use-cases that are not supported nicely yet.

For example with `strategy: matrix: include:` you can add entries to the matrix and with `strategy: matrix: exclude:` you can exclude some.
And also a matrix dimension value does not have to be a flat list of strings, but it can also be a list of objects.

**Do you have an example usage?**
Matrix from context variable:
```yml
matrix:
    version: ${{ github.event.client_payload.versions }}
```
Matrix with objects as values:
```yml
matrix:
    "environment":
        - "windows-2019"
        - "windows-2022"
        - "windows-latest"
    "distribution":
        - "wsl-id": "Debian"
          "user-id": "Debian"
          "match-pattern": "*Debian*"
          "default-absent-tool": "dos2unix"
        - "wsl-id": "Alpine"
          "user-id": "Alpine"
          "match-pattern": "*Alpine*"
          "default-absent-tool": "dos2unix"
```
Includes and Excludes:
```yml
matrix:
    "environment":
        - "windows-2019"
        - "windows-2022"
        - "windows-latest"
    "distribution":
        - "wsl-id": "Debian"
          "user-id": "Debian"
          "match-pattern": "*Debian*"
          "default-absent-tool": "dos2unix"
        - "wsl-id": "Alpine"
          "user-id": "Alpine"
          "match-pattern": "*Alpine*"
          "default-absent-tool": "dos2unix"
        - "wsl-id": "kali-linux"
          "user-id": "kali-linux"
          "match-pattern": "*Kali*"
          "default-absent-tool": "dos2unix"
        - "wsl-id": "openSUSE-Leap-15.2"
          "user-id": "openSUSE-Leap-15.2"
          "match-pattern": "*openSUSE*Leap*15.2*"
          "default-absent-tool": "which"
        - "wsl-id": "Ubuntu"
          "user-id": "Ubuntu-20.04"
          "match-pattern": "*Ubuntu*20.04*"
          "default-absent-tool": "dos2unix"
        - "wsl-id": "Ubuntu-18.04"
          "user-id": "Ubuntu-18.04"
          "match-pattern": "*Ubuntu*18.04*"
          "default-absent-tool": "dos2unix"
        - "wsl-id": "Ubuntu-16.04"
          "user-id": "Ubuntu-16.04"
          "match-pattern": "*Ubuntu*16.04*"
          "default-absent-tool": "dos2unix"
    "distribution2":
        - "wsl-id": "Debian"
          "user-id": "Debian"
          "match-pattern": "*Debian*"
          "default-absent-tool": "dos2unix"
    "exclude":
        - "environment": "windows-2019"
          "distribution":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
          "distribution2":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
        - "environment": "windows-2022"
          "distribution":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
          "distribution2":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
        - "environment": "windows-latest"
          "distribution":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
          "distribution2":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
    "include":
        - "environment": "windows-2019"
          "distribution":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
          "distribution2":
              "wsl-id": "Ubuntu"
              "user-id": "Ubuntu-20.04"
              "match-pattern": "*Ubuntu*20.04*"
              "default-absent-tool": "dos2unix"
        - "environment": "windows-2022"
          "distribution":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
          "distribution2":
              "wsl-id": "Ubuntu"
              "user-id": "Ubuntu-20.04"
              "match-pattern": "*Ubuntu*20.04*"
              "default-absent-tool": "dos2unix"
        - "environment": "windows-latest"
          "distribution":
              "wsl-id": "Debian"
              "user-id": "Debian"
              "match-pattern": "*Debian*"
              "default-absent-tool": "dos2unix"
          "distribution2":
              "wsl-id": "Ubuntu"
              "user-id": "Ubuntu-20.04"
              "match-pattern": "*Ubuntu*20.04*"
              "default-absent-tool": "dos2unix"
```

**Comment by Vampire** [comment]
Also `null` should be modelable, to for example model this which is not even possible right now on the one layer the matrices support:
```yaml
strategy:
    fail-fast: false
    matrix:
        environment:
            - windows-2019
            - windows-2022
            - windows-latest
        distribution:
            - id: invalid
              label: invalid
            - id: ''
              label: ''
            - id: null
              label: 'null'
```
