### ISSUE TITLE
[Bug] wrong line break

### ISSUE THREAD

**Issue by benkeil** [krzema12/github-workflows-kt#616]
# Action

The yaml has an unwanted line break. The first and second one are correct, but when the line is too long and contains expressions, there is a break.

```kotlin
val DEFAULT_AWS_REGION by Contexts.env

val workflow = workflow(...) {
  job(id = "deploy-dev", runsOn = RunnerType.UbuntuLatest) {
    uses(action = ConfigureAwsCredentialsV1(
      roleToAssume = "arn:aws:iam::${"1234567890".repeat(2)}:role/github-actions-role/${"1234567890".repeat(3)}",
      awsRegion = expr { DEFAULT_AWS_REGION }
    ))
    uses(action = ConfigureAwsCredentialsV1(
      roleToAssume = "arn:aws:iam::${"1234567890".repeat(0)}:role/github-actions-role/${expr { github.token }}",
      awsRegion = expr { DEFAULT_AWS_REGION }
    ))
    uses(action = ConfigureAwsCredentialsV1(
      roleToAssume = "arn:aws:iam::${"1234567890".repeat(1)}:role/github-actions-role/${expr { github.token }}",
      awsRegion = expr { DEFAULT_AWS_REGION }
    ))
    uses(action = ConfigureAwsCredentialsV1(
      roleToAssume = "arn:aws:iam::${"1234567890".repeat(2)}:role/github-actions-role/${expr { github.token }}",
      awsRegion = expr { DEFAULT_AWS_REGION }
    ))
  }
}
```

produces

```
...
    - id: step-10
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ DEFAULT_AWS_REGION }}
        role-to-assume: arn:aws:iam::12345678901234567890:role/github-actions-role/123456789012345678901234567890
    - id: step-11
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ DEFAULT_AWS_REGION }}
        role-to-assume: arn:aws:iam:::role/github-actions-role/${{ github.token }}
    - id: step-12
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ DEFAULT_AWS_REGION }}
        role-to-assume: arn:aws:iam::1234567890:role/github-actions-role/${{ github.token
          }}
    - id: step-13
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ DEFAULT_AWS_REGION }}
        role-to-assume: arn:aws:iam::12345678901234567890:role/github-actions-role/${{
          github.token }}
...
```

# Expected

valid yaml

# Actual

invalid yaml

# Workaround, if exists

_Manual adjustment of output YAML is not a workaround. Adjusting Kotlin code in a certain way is._

# Library version

v0.34.1
