### ISSUE TITLE
[Bug] String with value "null" and empty string in custom arguments are wrongly serialized

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-workflows-kt#627]
# Action

Use these custom arguments for a job:
```kts
_customArguments = mapOf(
    "strategy" to mapOf(
        "matrix" to mapOf(
            "distribution" to listOf(
                mapOf(
                    "id" to "invalid",
                    "label" to "invalid"
                ),
                mapOf(
                    "id" to "",
                    "label" to ""
                ),
                mapOf(
                    "id" to null,
                    "label" to "null"
                )
            )
        )
    )
)
```

# Expected

```yaml
strategy:
    matrix:
        distribution:
            - id: invalid
              label: invalid
            - id: ''
              label: ''
            - id: null
              label: 'null'
```

# Actual

```yaml
strategy:
  matrix:
    distribution:
    - id: invalid
      label: invalid
    - id:
      label:
    - id: null
      label: null
```

which is semantically the same as
```yaml
strategy:
  matrix:
    distribution:
    - id: invalid
      label: invalid
    - id: null
      label: null
    - id: null
      label: null
```

# Library version

v0.34.2
